/**
 * This file is auto-generated by KernelCMS. Do not edit by hand.
 * Run `kernel generate:types` to refresh it.
 */

export interface Authors {
  id: string
  name: string
  email?: string | null
  bio?: string | null
  createdAt?: string
  updatedAt?: string
}

export interface Categories {
  id: string
  name: string
  slug: string
  createdAt?: string
  updatedAt?: string
}

export interface Posts {
  id: string
  title: string
  slug: string
  excerpt?: string | null
  body?: unknown | null
  status?: 'draft' | 'published' | null
  featured?: boolean | null
  published_at?: string | null
  author?: string | null
  categories?: string[] | null
  tags?: Array<'release' | 'guide' | 'news' | 'tutorial'> | null
  createdAt?: string
  updatedAt?: string
}

export interface SiteSettings {
  id: string
  site_name?: string | null
  description?: string | null
  createdAt?: string
  updatedAt?: string
}

export interface KernelTypes {
  collections: {
    authors: Authors
    categories: Categories
    posts: Posts
  }
  globals: {
    site_settings: SiteSettings
  }
}
