import type { AnyField, ConfigField, CollectionConfig, GlobalConfig } from './types'
import { effectiveFields, optionValue } from './fields'

function pascal(slug: string): string {
  return slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join('')
}

function tsType(field: AnyField, indent: string): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'email':
    case 'code':
    case 'slug':
      return 'string'
    case 'number':
      return 'number'
    case 'boolean':
    case 'checkbox':
      return 'boolean'
    case 'date':
      return 'string'
    case 'richText':
      return "import('kernelcms/richtext').KernelRichText"
    case 'json':
      return 'unknown'
    case 'point':
      return '[number, number]'
    case 'select':
    case 'radio': {
      const union = field.options.map((o) => JSON.stringify(optionValue(o))).join(' | ') || 'string'
      return field.hasMany ? `Array<${union}>` : union
    }
    case 'relationship':
    case 'upload':
      return field.hasMany ? 'string[]' : 'string'
    case 'array':
      return `Array<${renderObject(field.fields, indent)}>`
    case 'group':
      return renderObject(field.fields, indent)
    default:
      return 'unknown'
  }
}

function renderObject(fieldsIn: ConfigField[], indent: string): string {
  const inner = `${indent}  `
  const lines = effectiveFields(fieldsIn).map(
    (f) => `${inner}${f.name}${f.required ? '' : '?'}: ${tsType(f, inner)}${f.required ? '' : ' | null'}`,
  )
  return `{\n${lines.join('\n')}\n${indent}}`
}

function renderInterface(name: string, fieldsIn: ConfigField[], timestamps: boolean): string {
  const lines = effectiveFields(fieldsIn).map(
    (f) => `  ${f.name}${f.required ? '' : '?'}: ${tsType(f, '  ')}${f.required ? '' : ' | null'}`,
  )
  const ts = timestamps ? '  createdAt?: string\n  updatedAt?: string\n' : ''
  return `export interface ${name} {\n  id: string\n${lines.join('\n')}\n${ts}}`
}

export interface CodegenInput {
  collections: CollectionConfig[]
  globals: GlobalConfig[]
}

/** Generate a TypeScript declaration string describing every collection and global. */
export function generateTypes(input: CodegenInput): string {
  const header = `/**
 * This file is auto-generated by KernelCMS. Do not edit by hand.
 * Run \`kernel generate:types\` to refresh it.
 */
/* eslint-disable */\n`

  const collectionTypes = input.collections
    .map((c) => renderInterface(pascal(c.slug), c.fields, c.timestamps ?? true))
    .join('\n\n')

  const globalTypes = input.globals
    .map((g) => renderInterface(pascal(g.slug), g.fields, true))
    .join('\n\n')

  const collectionMap = input.collections
    .map((c) => `    ${c.slug}: ${pascal(c.slug)}`)
    .join('\n')
  const globalMap = input.globals.map((g) => `    ${g.slug}: ${pascal(g.slug)}`).join('\n')

  const registry = `export interface KernelTypes {
  collections: {
${collectionMap || '    [slug: string]: { id: string }'}
  }
  globals: {
${globalMap || '    [slug: string]: Record<string, unknown>'}
  }
}`

  return [header, collectionTypes, globalTypes, registry].filter(Boolean).join('\n\n') + '\n'
}
