/**
 * OpenID Connect (OIDC) SSO — a strict, dependency-free id_token verifier built
 * on `node:crypto` + `fetch`. It returns an {@link OAuthProvider}, so OIDC reuses
 * the exact same sign-in/provisioning path as plain OAuth (`loginWithOAuth`).
 *
 * What makes this trustworthy (and what Loki will probe):
 *  - The id_token signature is verified against the issuer's JWKS. We REJECT
 *    `alg:none` and every HS* (shared-secret) algorithm — only asymmetric algs
 *    are accepted, which defeats the classic alg-confusion attack where an
 *    attacker re-signs a forged token with the (public) RSA key as an HMAC key.
 *  - Claims are validated: `iss`, `aud`, `exp`, `iat`/`nbf`, and the `nonce` we
 *    generated. Nothing from an unverified token (or userinfo) is ever trusted.
 *  - CSRF/replay/interception defences: `state`, `nonce`, and PKCE (S256), all
 *    generated by the caller (the server) with `crypto.randomBytes`/`randomUUID`.
 */
import {
  createHash,
  createPublicKey,
  randomBytes,
  timingSafeEqual,
  verify as cryptoVerify,
  type JsonWebKey,
  type KeyObject,
} from 'node:crypto'
import type { OAuthProfile, OAuthProvider } from './oauth'

// ---------------------------------------------------------------------------
// Algorithm allowlist. Asymmetric only — reject `none` and all HS* (HMAC) algs.
// ---------------------------------------------------------------------------

/** Maps a JOSE `alg` to the `node:crypto` verify parameters. RSA-PSS (PS-family)
 *  is intentionally omitted to keep the surface small; the RS and ES families
 *  cover every listed enterprise IdP (Okta, Auth0, Entra, Google, OneLogin). */
const ALG: Record<string, { hash: string; key: 'rsa' | 'ec'; dsaEncoding?: 'ieee-p1363' }> = {
  RS256: { hash: 'sha256', key: 'rsa' },
  RS384: { hash: 'sha384', key: 'rsa' },
  RS512: { hash: 'sha512', key: 'rsa' },
  ES256: { hash: 'sha256', key: 'ec', dsaEncoding: 'ieee-p1363' },
  ES384: { hash: 'sha384', key: 'ec', dsaEncoding: 'ieee-p1363' },
}

/** Clock skew tolerated when checking `exp`/`iat`/`nbf`, in seconds. */
const CLOCK_SKEW_S = 60

// ---------------------------------------------------------------------------
// JWT primitives (no dependency — base64url decode + claim shapes).
// ---------------------------------------------------------------------------

interface JwtHeader {
  alg: string
  kid?: string
  typ?: string
}

interface IdTokenClaims {
  iss?: string
  aud?: string | string[]
  exp?: number
  iat?: number
  nbf?: number
  nonce?: string
  sub?: string
  email?: string
  email_verified?: boolean | string
  name?: string
  azp?: string
}

interface Jwk {
  kid?: string
  kty?: string
  use?: string
  alg?: string
  [k: string]: unknown
}

interface OidcDiscovery {
  issuer: string
  authorization_endpoint: string
  token_endpoint: string
  jwks_uri: string
}

function b64urlToString(seg: string): string {
  return Buffer.from(seg, 'base64url').toString('utf8')
}

/** Parse a JWS compact serialization without trusting any of it yet. */
function decodeJwt(token: string): {
  header: JwtHeader
  claims: IdTokenClaims
  signingInput: string
  signature: Buffer
} {
  const parts = token.split('.')
  if (parts.length !== 3) throw new OidcError('id_token is not a well-formed JWS.')
  const [h, p, s] = parts as [string, string, string]
  let header: JwtHeader
  let claims: IdTokenClaims
  try {
    header = JSON.parse(b64urlToString(h)) as JwtHeader
    claims = JSON.parse(b64urlToString(p)) as IdTokenClaims
  } catch {
    throw new OidcError('id_token header/payload is not valid JSON.')
  }
  return { header, claims, signingInput: `${h}.${p}`, signature: Buffer.from(s, 'base64url') }
}

// ---------------------------------------------------------------------------
// Error type — extends a typed base so callers can branch on it.
// ---------------------------------------------------------------------------

export class OidcError extends Error {
  readonly code = 'OIDC_ERROR'
  constructor(message: string) {
    super(message)
    this.name = 'OidcError'
  }
}

// ---------------------------------------------------------------------------
// Caches (per-provider instance, captured in the closure below).
// ---------------------------------------------------------------------------

interface JwksCache {
  keys: Jwk[]
  fetchedAt: number
}

/** Constant-time string compare (used for nonce). Length leak is acceptable —
 *  nonces are fixed-length here — but we still avoid early-out on content. */
function safeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a, 'utf8')
  const bb = Buffer.from(b, 'utf8')
  if (ab.length !== bb.length) return false
  return timingSafeEqual(ab, bb)
}

// ---------------------------------------------------------------------------
// PKCE helpers (exported for the server to generate a verifier/challenge pair).
// ---------------------------------------------------------------------------

/** Generate a high-entropy PKCE verifier (RFC 7636: 43–128 unreserved chars). */
export function pkceVerifier(): string {
  return randomBytes(32).toString('base64url')
}

/** Derive the S256 challenge for a verifier. */
export function pkceChallenge(verifier: string): string {
  return createHash('sha256').update(verifier).digest('base64url')
}

// ---------------------------------------------------------------------------
// The provider.
// ---------------------------------------------------------------------------

export interface OidcProviderOptions {
  /** The IdP issuer, e.g. `https://example.okta.com` or an Auth0 tenant URL.
   *  `${issuer}/.well-known/openid-configuration` must resolve. */
  issuer: string
  clientId: string
  clientSecret: string
  /** Route/name override. Defaults to `'oidc'`. */
  name?: string
  /** Extra scopes. `openid` is always included; `email profile` are added by
   *  default so we get an email + name back. */
  scopes?: string[]
}

/** Strip a single trailing slash so discovery-URL joins are predictable. */
function trimSlash(s: string): string {
  return s.endsWith('/') ? s.slice(0, -1) : s
}

export function oidcProvider(opts: OidcProviderOptions): OAuthProvider {
  const issuer = trimSlash(opts.issuer)
  const name = opts.name ?? 'oidc'
  const scope = Array.from(new Set(['openid', 'email', 'profile', ...(opts.scopes ?? [])])).join(' ')

  let discovery: Promise<OidcDiscovery> | undefined
  let resolved: OidcDiscovery | undefined
  let jwks: JwksCache | undefined

  async function getDiscovery(): Promise<OidcDiscovery> {
    if (!discovery) {
      discovery = (async () => {
        const url = `${issuer}/.well-known/openid-configuration`
        const res = await fetch(url, { headers: { accept: 'application/json' } })
        if (!res.ok) throw new OidcError(`OIDC discovery failed (${res.status}).`)
        const doc = (await res.json()) as Partial<OidcDiscovery>
        if (!doc.issuer || !doc.authorization_endpoint || !doc.token_endpoint || !doc.jwks_uri) {
          throw new OidcError('OIDC discovery document is missing required fields.')
        }
        // The discovered issuer MUST match the configured one (per OIDC Discovery
        // §4.3) — a mismatch means we fetched the wrong/spoofed metadata.
        if (trimSlash(doc.issuer) !== issuer) {
          throw new OidcError('OIDC discovery `issuer` does not match the configured issuer.')
        }
        const out: OidcDiscovery = {
          issuer: doc.issuer,
          authorization_endpoint: doc.authorization_endpoint,
          token_endpoint: doc.token_endpoint,
          jwks_uri: doc.jwks_uri,
        }
        resolved = out
        return out
      })().catch((e) => {
        // Don't pin a failed promise — allow a later retry.
        discovery = undefined
        throw e
      })
    }
    return discovery
  }

  // Warm the discovery cache so the (synchronous) authorizationUrl can use the
  // real authorization_endpoint on the first request. Best-effort: failures are
  // retried on the next exchange, which is where verification actually happens.
  void getDiscovery().catch(() => {})

  async function fetchJwks(jwksUri: string): Promise<Jwk[]> {
    const res = await fetch(jwksUri, { headers: { accept: 'application/json' } })
    if (!res.ok) throw new OidcError(`JWKS fetch failed (${res.status}).`)
    const doc = (await res.json()) as { keys?: Jwk[] }
    if (!Array.isArray(doc.keys)) throw new OidcError('JWKS response has no `keys` array.')
    return doc.keys
  }

  /** Find the JWK for a `kid`, refreshing the cache ONCE on a miss (handles key
   *  rotation without hammering the JWKS endpoint on every unknown kid). */
  async function jwkForKid(jwksUri: string, kid: string): Promise<Jwk> {
    if (!jwks) jwks = { keys: await fetchJwks(jwksUri), fetchedAt: Date.now() }
    let jwk = jwks.keys.find((k) => k.kid === kid)
    if (!jwk) {
      jwks = { keys: await fetchJwks(jwksUri), fetchedAt: Date.now() }
      jwk = jwks.keys.find((k) => k.kid === kid)
    }
    if (!jwk) throw new OidcError('No JWKS key matches the id_token `kid`.')
    return jwk
  }

  function importKey(jwk: Jwk): KeyObject {
    try {
      // `format: 'jwk'` lets node import the public key directly from the JWK.
      return createPublicKey({ key: jwk as unknown as JsonWebKey, format: 'jwk' })
    } catch {
      throw new OidcError('Failed to import the JWKS key.')
    }
  }

  async function verifyIdToken(idToken: string, expectedNonce: string | undefined): Promise<IdTokenClaims> {
    const { header, claims, signingInput, signature } = decodeJwt(idToken)

    // 1) Algorithm: asymmetric allowlist only. Rejects `none` and every HS*.
    const spec = ALG[header.alg]
    if (!spec) throw new OidcError(`id_token alg "${header.alg}" is not allowed.`)
    if (!header.kid) throw new OidcError('id_token header is missing `kid`.')

    // 2) Signature: verify over `header.payload` with the JWKS key for this kid.
    const { jwks_uri } = await getDiscovery()
    const jwk = await jwkForKid(jwks_uri, header.kid)
    // Defence in depth: if the JWK pins a `kty`, it must match the alg family.
    if (jwk.kty && ((spec.key === 'rsa' && jwk.kty !== 'RSA') || (spec.key === 'ec' && jwk.kty !== 'EC'))) {
      throw new OidcError('JWKS key type does not match the id_token `alg`.')
    }
    const key = importKey(jwk)
    const ok = cryptoVerify(
      spec.hash,
      Buffer.from(signingInput),
      spec.dsaEncoding ? { key, dsaEncoding: spec.dsaEncoding } : key,
      signature,
    )
    if (!ok) throw new OidcError('id_token signature verification failed.')

    // 3) Claims. Order matters less than completeness — all must hold.
    const now = Math.floor(Date.now() / 1000)
    if (!claims.iss || trimSlash(claims.iss) !== issuer) throw new OidcError('id_token `iss` mismatch.')

    const aud = Array.isArray(claims.aud) ? claims.aud : claims.aud ? [claims.aud] : []
    if (!aud.includes(opts.clientId)) throw new OidcError('id_token `aud` does not include the client id.')
    // When multiple audiences are present, `azp` (if present) must be our client.
    if (aud.length > 1 && claims.azp && claims.azp !== opts.clientId) {
      throw new OidcError('id_token `azp` is not the configured client.')
    }

    if (typeof claims.exp !== 'number' || claims.exp + CLOCK_SKEW_S < now) {
      throw new OidcError('id_token is expired.')
    }
    if (typeof claims.iat === 'number' && claims.iat - CLOCK_SKEW_S > now) {
      throw new OidcError('id_token `iat` is in the future.')
    }
    if (typeof claims.nbf === 'number' && claims.nbf - CLOCK_SKEW_S > now) {
      throw new OidcError('id_token is not yet valid (`nbf`).')
    }

    // 4) Nonce: must equal the one we generated for this flow (replay defence).
    if (expectedNonce !== undefined) {
      if (typeof claims.nonce !== 'string' || !safeEqual(claims.nonce, expectedNonce)) {
        throw new OidcError('id_token `nonce` does not match.')
      }
    }

    if (typeof claims.sub !== 'string' || claims.sub.length === 0) {
      throw new OidcError('id_token has no `sub`.')
    }
    return claims
  }

  return {
    name,
    needsNonce: true,

    authorizationUrl({ redirectUri, state, nonce, codeChallenge }) {
      // Discovery is async, but authorizationUrl is sync in the interface. Use
      // the warmed discovery cache when available; otherwise fall back to the
      // conventional `${issuer}/authorize` path. The exchange step always does
      // full discovery + id_token verification regardless, so a stale/guessed
      // authorize URL can never weaken security — at worst the IdP rejects it.
      const authorize = resolved?.authorization_endpoint ?? `${issuer}/authorize`
      const params = new URLSearchParams({
        client_id: opts.clientId,
        redirect_uri: redirectUri,
        response_type: 'code',
        scope,
        state,
      })
      if (nonce) params.set('nonce', nonce)
      if (codeChallenge) {
        params.set('code_challenge', codeChallenge)
        params.set('code_challenge_method', 'S256')
      }
      return `${authorize}?${params.toString()}`
    },

    async exchangeCode({ code, redirectUri, nonce, codeVerifier }) {
      const { token_endpoint } = await getDiscovery()
      const body = new URLSearchParams({
        grant_type: 'authorization_code',
        code,
        redirect_uri: redirectUri,
        client_id: opts.clientId,
        client_secret: opts.clientSecret,
      })
      if (codeVerifier) body.set('code_verifier', codeVerifier)

      const res = await fetch(token_endpoint, {
        method: 'POST',
        headers: { 'content-type': 'application/x-www-form-urlencoded', accept: 'application/json' },
        body: body.toString(),
      })
      if (!res.ok) throw new OidcError(`OIDC token exchange failed (${res.status}).`)
      const token = (await res.json()) as { id_token?: string }
      if (!token.id_token) throw new OidcError('OIDC token response had no id_token.')

      const claims = await verifyIdToken(token.id_token, nonce)
      const emailVerified = claims.email_verified === true || claims.email_verified === 'true'
      const profile: OAuthProfile = {
        id: claims.sub as string,
        email: claims.email ?? '',
        emailVerified,
        name: claims.name,
      }
      return profile
    },
  }
}

// ---------------------------------------------------------------------------
// Enterprise presets — each is just `oidcProvider` with the right issuer.
// ---------------------------------------------------------------------------

/** Okta. `domain` is the Okta org, e.g. `dev-123.okta.com` (no scheme needed). */
export function oktaSSO(opts: {
  domain: string
  clientId: string
  clientSecret: string
  name?: string
  scopes?: string[]
}): OAuthProvider {
  return oidcProvider({ ...opts, name: opts.name ?? 'okta', issuer: withScheme(opts.domain) })
}

/** Auth0. `domain` is the tenant domain, e.g. `your-tenant.us.auth0.com`. */
export function auth0SSO(opts: {
  domain: string
  clientId: string
  clientSecret: string
  name?: string
  scopes?: string[]
}): OAuthProvider {
  return oidcProvider({ ...opts, name: opts.name ?? 'auth0', issuer: withScheme(opts.domain) })
}

/** Microsoft Entra ID (Azure AD). `tenantId` is the directory (tenant) GUID,
 *  or `organizations`/`common` for multi-tenant. */
export function entraSSO(opts: {
  tenantId: string
  clientId: string
  clientSecret: string
  name?: string
  scopes?: string[]
}): OAuthProvider {
  return oidcProvider({
    clientId: opts.clientId,
    clientSecret: opts.clientSecret,
    name: opts.name ?? 'entra',
    scopes: opts.scopes,
    issuer: `https://login.microsoftonline.com/${opts.tenantId}/v2.0`,
  })
}

/** Google Workspace (Google Identity). The issuer is shared across Google. */
export function googleWorkspaceSSO(opts: {
  clientId: string
  clientSecret: string
  name?: string
  scopes?: string[]
}): OAuthProvider {
  return oidcProvider({
    clientId: opts.clientId,
    clientSecret: opts.clientSecret,
    name: opts.name ?? 'google-workspace',
    scopes: opts.scopes,
    issuer: 'https://accounts.google.com',
  })
}

/** OneLogin. `domain` is the subdomain host, e.g. `your-org.onelogin.com`. */
export function oneLoginSSO(opts: {
  domain: string
  clientId: string
  clientSecret: string
  name?: string
  scopes?: string[]
}): OAuthProvider {
  return oidcProvider({
    ...opts,
    name: opts.name ?? 'onelogin',
    issuer: `${trimSlash(withScheme(opts.domain))}/oidc/2`,
  })
}

/** Add `https://` when the caller passed a bare host. */
function withScheme(domain: string): string {
  return /^https?:\/\//.test(domain) ? domain : `https://${domain}`
}
