import { defineConfig } from '@kernel/core'
import type { Kernel } from '@kernel/core'
import { sqliteAdapter } from '@kernel/db-sqlite'

/**
 * Content model: Blog (blog).
 * Posts, authors, categories — the classic editorial model
 *
 * Generated by create-kernel. Edit freely — add a field, delete kernelcms.db,
 * restart, and the migration is generated automatically.
 */
export const config = defineConfig({
  secret: process.env.KERNEL_SECRET ?? 'start-dev-secret',
  db: sqliteAdapter({ url: process.env.KERNEL_DB_URL ?? 'file:./kernelcms.db' }),
  collections: [
    {
      slug: "authors",
      admin: {
        useAsTitle: "name",
      },
      access: { read: () => true },
      fields: [
        {
          name: "name",
          type: "text",
          required: true,
        },
        {
          name: "bio",
          type: "textarea",
        },
      ],
    },
    {
      slug: "categories",
      admin: {
        useAsTitle: "name",
      },
      access: { read: () => true },
      fields: [
        {
          name: "name",
          type: "text",
          required: true,
        },
        {
          name: "slug",
          type: "slug",
          required: true,
          unique: true,
        },
      ],
    },
    {
      slug: "posts",
      admin: {
        useAsTitle: "title",
      },
      access: { read: () => true },
      fields: [
        {
          name: "title",
          type: "text",
          required: true,
        },
        {
          name: "slug",
          type: "slug",
          required: true,
          unique: true,
          index: true,
        },
        {
          name: "excerpt",
          type: "textarea",
        },
        {
          name: "body",
          type: "textarea",
        },
        {
          name: "status",
          type: "select",
          options: [
            "draft",
            "published",
          ],
          defaultValue: "published",
          index: true,
        },
        {
          name: "published_at",
          type: "date",
        },
        {
          name: "author",
          type: "relationship",
          relationTo: "authors",
        },
        {
          name: "categories",
          type: "relationship",
          relationTo: "categories",
          hasMany: true,
        },
      ],
    },
  ],
  globals: [
    {
      slug: "site_settings",
      access: { read: () => true },
      fields: [
        {
          name: "site_name",
          type: "text",
          defaultValue: "The Kernel Blog",
        },
        {
          name: "tagline",
          type: "text",
          defaultValue: "Built with KernelCMS on TanStack Start",
        },
      ],
    },
  ],
})

/** Drives the generic home + detail routes (which field is the title, etc.). */
export const view = {
    primary: "posts",
    settings: "site_settings",
    title: "title",
    excerpt: "excerpt",
    date: "published_at",
    slug: "slug",
  } as const

/** Seed rows for first boot. `@ref` values resolve to ids created earlier in the run. */
const seedData: Record<string, any> = {
    authors: [
      {
        _ref: "ada",
        name: "Ada Lovelace",
        bio: "Wrote the first algorithm intended for a machine.",
      },
      {
        _ref: "grace",
        name: "Grace Hopper",
        bio: "Pioneered machine-independent programming languages.",
      },
    ],
    categories: [
      {
        _ref: "eng",
        name: "Engineering",
        slug: "engineering",
      },
      {
        _ref: "product",
        name: "Product",
        slug: "product",
      },
    ],
    posts: [
      {
        title: "Hello from KernelCMS on TanStack Start",
        slug: "hello-kernelcms",
        excerpt: "Server-rendered by TanStack Start, content read from the KernelCMS Local API — no HTTP round-trip.",
        body: "Everything you see flows from a single config.ts. The same operations are also a REST + typed RPC API.",
        status: "published",
        published_at: "2026-01-03",
        author: "@ada",
        categories: [
          "@eng",
        ],
      },
      {
        title: "Choose Everything: The Adapter Pattern",
        slug: "choose-everything",
        excerpt: "Database, storage, auth, search — every infrastructure concern is a swappable adapter.",
        body: "The core never imports a driver. The same content config runs on Postgres, SQLite, or MongoDB.",
        status: "published",
        published_at: "2026-01-02",
        author: "@ada",
        categories: [
          "@eng",
          "@product",
        ],
      },
      {
        title: "Type-safe content, end to end",
        slug: "type-safe-content",
        excerpt: "Model content as code and get generated TypeScript types and a typed client for free.",
        body: "Define a collection once and get migrations, validation, access control, and types your frontend imports.",
        status: "published",
        published_at: "2026-01-01",
        author: "@grace",
        categories: [
          "@product",
        ],
      },
    ],
    _globals: {
      site_settings: {
        site_name: "The Kernel Blog",
        tagline: "Built with KernelCMS on TanStack Start",
      },
    },
  }

function resolveRow(row: Record<string, any>, refs: Record<string, string>): Record<string, any> {
  const out: Record<string, any> = {}
  for (const [key, value] of Object.entries(row)) {
    if (key === '_ref') continue
    if (typeof value === 'string' && value.startsWith('@')) out[key] = refs[value.slice(1)]
    else if (Array.isArray(value))
      out[key] = value.map((v) => (typeof v === 'string' && v.startsWith('@') ? refs[v.slice(1)] : v))
    else out[key] = value
  }
  return out
}

/** Idempotent seed run once on first boot. */
export async function seed(kernel: Kernel): Promise<void> {
  const sys = { overrideAccess: true } as const
  const refs: Record<string, string> = {}
  for (const collection of config.collections) {
    const rows: Record<string, any>[] = seedData[collection.slug] ?? []
    for (const row of rows) {
      const created = await kernel.create({ collection: collection.slug, data: resolveRow(row, refs), ...sys })
      if (row._ref) refs[row._ref] = created.id
    }
  }
  const globals: Record<string, Record<string, any>> = seedData._globals ?? {}
  for (const slug of Object.keys(globals)) {
    await kernel.updateGlobal({ slug, data: globals[slug], ...sys })
  }
}
